version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - composer install --no-dev --prefer-dist --optimize-autoloader
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Building frontend assets with Vite...
      - npm run build

artifacts:
  files:
    - '**/*'
  name: build-artifact
